import { useState } from "react";
import { CheckCircle2, Clock3, FileWarning, RefreshCw, XCircle } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

const statuses = ["pending", "approved", "rejected", "all"] as const;
type Status = (typeof statuses)[number];

export default function AdminModerationAppeals() {
  const { user } = useAuth();
  const [status, setStatus] = useState<Status>("pending");
  const [sort, setSort] = useState<"newest" | "oldest">("newest");
  const [page, setPage] = useState(1);
  const [note, setNote] = useState<Record<number, string>>({});
  const appeals = trpc.moderationAppeals.adminList.useQuery({ status, sort, page, limit: 25 }, { enabled: user?.role === "admin", retry: false, staleTime: 10_000 });
  const resolve = trpc.moderationAppeals.adminResolve.useMutation({ onSuccess: (_, input) => { toast.success(`Appeal ${input.status}.`); void appeals.refetch(); }, onError: (error) => toast.error(error.message || "Could not resolve appeal.") });

  if (user?.role !== "admin") return <main className="grid min-h-screen place-items-center bg-[#080b14] p-6 text-white"><Card className="border-white/10 bg-white/5 p-8 text-center"><FileWarning className="mx-auto h-10 w-10 text-rose-300" /><h1 className="mt-4 text-2xl font-bold">Administrator access required</h1><p className="mt-2 text-slate-400">This review queue is restricted to authorized moderators.</p></Card></main>;

  return <main className="min-h-screen bg-[#080b14] px-4 py-8 text-white sm:px-8"><div className="mx-auto max-w-6xl space-y-6">
    <header><p className="text-xs font-semibold uppercase tracking-[0.24em] text-indigo-300">TRILLIONER LINK / Trust & safety</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold">Moderation appeals</h1><p className="mt-2 text-slate-400">Review automated decisions with the original content snapshot and user explanation.</p></div><Button variant="outline" className="border-white/15 bg-transparent text-white hover:bg-white/10 hover:text-white" onClick={() => void appeals.refetch()}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button></div></header>
    <Card className="border-white/10 bg-white/[0.045] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2" role="tablist" aria-label="Appeal status filter">{statuses.map((item) => <button key={item} role="tab" aria-selected={status === item} onClick={() => { setStatus(item); setPage(1); }} className={`rounded-full px-4 py-2 text-sm capitalize transition ${status === item ? "bg-white text-slate-950" : "bg-white/5 text-slate-300 hover:bg-white/10"}`}>{item}</button>)}</div><label className="flex items-center gap-2 text-sm text-slate-400">Sort<select value={sort} onChange={(event) => { setSort(event.target.value as typeof sort); setPage(1); }} className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-white"><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label></div></Card>
    {appeals.isLoading && <Card className="border-white/10 bg-white/[0.045] p-8 text-center text-slate-400">Loading appeals…</Card>}
    {appeals.error && <Card className="border-rose-400/30 bg-rose-500/10 p-8 text-rose-200">Could not load appeals. Confirm your administrator session and try again.</Card>}
    {!appeals.isLoading && !appeals.error && appeals.data?.records.length === 0 && <Card className="border-white/10 bg-white/[0.045] p-10 text-center"><Clock3 className="mx-auto h-9 w-9 text-slate-500" /><p className="mt-3 font-medium">No {status === "all" ? "appeals" : `${status} appeals`} found.</p><p className="mt-1 text-sm text-slate-500">The queue will update when a user submits an appeal.</p></Card>}
    <div className="space-y-4">{appeals.data?.records.map((appeal) => <Card key={appeal.id} className="border-white/10 bg-white/[0.045] p-5"><div className="flex flex-col gap-4 lg:flex-row lg:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-indigo-500/15 px-2.5 py-1 text-xs font-semibold capitalize text-indigo-200">{appeal.contentType}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${appeal.status === "pending" ? "bg-amber-500/15 text-amber-200" : appeal.status === "approved" ? "bg-emerald-500/15 text-emerald-200" : "bg-rose-500/15 text-rose-200"}`}>{appeal.status}</span><span className="text-xs text-slate-500">{new Date(appeal.createdAt).toLocaleString()}</span></div><p className="mt-4 text-sm text-slate-300"><span className="font-semibold text-white">Appeal reason:</span> {appeal.appealReason}</p><details className="mt-3"><summary className="cursor-pointer text-sm text-slate-400 hover:text-white">View content snapshot</summary><p className="mt-2 whitespace-pre-wrap rounded-lg bg-black/20 p-3 text-sm text-slate-300">{appeal.content}</p>{appeal.mediaUrl && <a className="mt-2 inline-block text-sm text-indigo-300 underline" href={appeal.mediaUrl} target="_blank" rel="noreferrer">Open attached media</a>}</details>{appeal.reviewerNote && <p className="mt-3 text-sm text-slate-400">Reviewer note: {appeal.reviewerNote}</p>}</div>{appeal.status === "pending" && <div className="w-full shrink-0 lg:max-w-sm"><Textarea value={note[appeal.id] ?? ""} onChange={(event) => setNote((current) => ({ ...current, [appeal.id]: event.target.value }))} placeholder="Optional reviewer note" maxLength={2000} rows={3} className="border-white/10 bg-black/20 text-white" /><div className="mt-3 flex gap-2"><Button disabled={resolve.isPending} onClick={() => resolve.mutate({ appealId: appeal.id, status: "approved", reviewerNote: note[appeal.id] })} className="flex-1 bg-emerald-600 hover:bg-emerald-500"><CheckCircle2 className="mr-1.5 h-4 w-4" />Approve</Button><Button disabled={resolve.isPending} onClick={() => resolve.mutate({ appealId: appeal.id, status: "rejected", reviewerNote: note[appeal.id] })} variant="outline" className="flex-1 border-rose-400/30 bg-transparent text-rose-200 hover:bg-rose-500/10"><XCircle className="mr-1.5 h-4 w-4" />Reject</Button></div></div>}</div></Card>)}</div>
    {appeals.data && appeals.data.total > 0 && <div className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[0.045] p-3 text-sm text-slate-400"><span>Page {appeals.data.page} · {appeals.data.total} total appeals</span><div className="flex gap-2"><Button variant="outline" disabled={!appeals.data.hasPrevious || appeals.isFetching} onClick={() => setPage((value) => Math.max(1, value - 1))} className="border-white/15 bg-transparent text-white hover:bg-white/10 hover:text-white">Previous</Button><Button variant="outline" disabled={!appeals.data.hasNext || appeals.isFetching} onClick={() => setPage((value) => value + 1)} className="border-white/15 bg-transparent text-white hover:bg-white/10 hover:text-white">Next</Button></div></div>}
  </div></main>;
}
