import { useMemo, useState } from "react";
import { BarChart3, Download, Eye, Heart, LineChart as LineChartIcon, MessageCircle, Moon, Share2, Sun, Users, Video } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { useLocation } from "wouter";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import "./CreatorDashboard.css";

function compact(value: number) { return Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(value); }
function dateString(date: Date) { return date.toISOString().slice(0, 10); }
export function getAnalyticsTheme(storage?: Pick<Storage, "getItem">): "dark" | "light" { return storage?.getItem("creator-analytics-theme") === "light" ? "light" : "dark"; }
export function buildAnalyticsCsv(data: { subscribers: number; views: number; likes: number; comments: number; shares: number; engagementRate: number; recentVideos: Array<{ title: string; views: number; likes: number; comments: number; createdAt: Date | string }> }, days: number) {
  const escape = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`;
  const rows: Array<Array<string | number>> = [["Metric", "Value", "Window"], ["Subscribers", data.subscribers, `${days} days`], ["Views", data.views, `${days} days`], ["Likes", data.likes, `${days} days`], ["Comments", data.comments, `${days} days`], ["Shares", data.shares, `${days} days`], ["Engagement rate", `${data.engagementRate}%`, `${days} days`], [], ["Video", "Views", "Likes", "Comments", "Published"]];
  data.recentVideos.forEach((video) => rows.push([video.title, video.views, video.likes, video.comments, new Date(video.createdAt).toISOString()]));
  return rows.map((row) => row.map((value) => escape(value ?? "")).join(",")).join("\n");
}
function AnalyticsSkeleton() { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <div key={index} className="h-32 animate-pulse rounded-2xl border border-white/10 bg-white/5" />)}</div>; }

export default function CreatorDashboard() {
  const { isAuthenticated } = useAuth();
  const [, setLocation] = useLocation();
  const initialEnd = useMemo(() => dateString(new Date()), []);
  const initialStart = useMemo(() => { const date = new Date(); date.setDate(date.getDate() - 29); return dateString(date); }, []);
  const [startDate, setStartDate] = useState(initialStart);
  const [endDate, setEndDate] = useState(initialEnd);
  const [analyticsDark, setAnalyticsDark] = useState(() => getAnalyticsTheme(typeof window === "undefined" ? undefined : window.localStorage) === "dark");
  const days = Math.max(7, Math.min(366, Math.ceil((new Date(`${endDate}T23:59:59`).getTime() - new Date(`${startDate}T00:00:00`).getTime()) / 86_400_000) + 1));
  const analytics = trpc.creatorAnalytics.getOverview.useQuery({ days, startDate, endDate }, { enabled: isAuthenticated && startDate <= endDate, retry: false, staleTime: 30_000, gcTime: 5 * 60_000, refetchOnWindowFocus: false });
  const exportCsv = () => { if (!analytics.data) return; const csv = buildAnalyticsCsv(analytics.data, days); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `trillioner-link-creator-analytics-${startDate}-to-${endDate}.csv`; anchor.click(); URL.revokeObjectURL(url); toast.success("Analytics CSV downloaded"); };
  const toggleAnalyticsTheme = () => setAnalyticsDark((previous) => { const next = !previous; window.localStorage.setItem("creator-analytics-theme", next ? "dark" : "light"); return next; });
  const cards = useMemo(() => analytics.data ? [{ label: "Subscribers", value: compact(analytics.data.subscribers), icon: Users, tone: "text-indigo-300" }, { label: "Video views", value: compact(analytics.data.views), icon: Eye, tone: "text-cyan-300" }, { label: "Total likes", value: compact(analytics.data.likes), icon: Heart, tone: "text-rose-300" }, { label: "Engagement rate", value: `${analytics.data.engagementRate}%`, icon: BarChart3, tone: "text-emerald-300" }] : [], [analytics.data]);
  const chartData = analytics.data?.series ?? [];
  if (!isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#080b14] p-6 text-white"><Card className="max-w-md border-white/10 bg-white/5 p-8 text-center"><h1 className="text-2xl font-bold">Creator analytics is private</h1><p className="mt-2 text-slate-300">Sign in to view your real subscription and engagement performance.</p><Button className="mt-5" onClick={() => setLocation("/login")}>Sign in</Button></Card></main>;
  return <main data-analytics-theme={analyticsDark ? "dark" : "light"} className={`creator-analytics-shell min-h-screen px-4 py-8 sm:px-8 ${analyticsDark ? "bg-[#080b14] text-white" : "bg-slate-50 text-slate-950"}`}><div className="mx-auto max-w-6xl space-y-8">
    <header className="flex flex-col gap-4 border-b border-white/10 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-indigo-300">TRILLIONER LINK / Creator studio</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Your channel, measured clearly.</h1><p className="mt-2 max-w-xl text-slate-300">Track subscribers, reach, and meaningful engagement from published Creator content.</p></div><div className="flex flex-wrap items-center gap-2"><button onClick={toggleAnalyticsTheme} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-300 hover:bg-white/10" aria-label="Toggle analytics dark mode">{analyticsDark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}{analyticsDark ? "Light" : "Dark"}</button><Button variant="outline" disabled={!analytics.data} onClick={exportCsv} className="inline-flex items-center gap-2 border-white/10 bg-white/5 text-slate-300 hover:bg-white/10 hover:text-white"><Download className="h-4 w-4" />Export CSV</Button></div></header>
    <Card className="border-white/10 bg-white/[0.045] p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold">Custom date range</p><p className="mt-1 text-xs text-slate-400">Choose the exact window used by every metric and chart.</p></div><div className="flex flex-wrap items-end gap-3"><label className="grid gap-1 text-xs text-slate-400">From<input type="date" value={startDate} max={endDate} onChange={(event) => setStartDate(event.target.value)} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm text-white" /></label><label className="grid gap-1 text-xs text-slate-400">To<input type="date" value={endDate} min={startDate} onChange={(event) => setEndDate(event.target.value)} className="rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm text-white" /></label></div></div>{startDate > endDate && <p className="mt-3 text-sm text-rose-300">Start date must be before end date.</p>}</Card>
    {analytics.isLoading && <AnalyticsSkeleton />}{analytics.error && <Card className="border-rose-400/30 bg-rose-500/10 p-6"><p className="font-semibold text-rose-200">Analytics are temporarily unavailable.</p><p className="mt-1 text-sm text-rose-100/70">Try another date range shortly.</p></Card>}{analytics.data && <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map((card) => { const Icon = card.icon; return <Card key={card.label} className="border-white/10 bg-white/[0.045] p-5"><div className="flex items-center justify-between"><span className={`rounded-xl bg-white/10 p-2 ${card.tone}`}><Icon className="h-5 w-5" /></span><span className="text-xs text-slate-500">{analytics.data.startDate} → {analytics.data.endDate}</span></div><p className="mt-5 text-sm text-slate-400">{card.label}</p><p className="mt-1 text-3xl font-bold">{card.value}</p>{analytics.data.comparison && (() => { const key = ({ Subscribers: "subscribers", "Video views": "views", "Total likes": "likes", "Engagement rate": "views" } as const)[card.label as "Subscribers" | "Video views" | "Total likes" | "Engagement rate"]; const change = analytics.data.comparison[key]; return <p className={`mt-2 text-xs font-medium ${change.percent >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{change.percent >= 0 ? "↑" : "↓"} {Math.abs(change.percent)}% vs previous period</p>; })()}</Card>; })}</div>
      <Card className="border-white/10 bg-white/[0.045] p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold">Period comparison</h2><p className="mt-1 text-sm text-slate-400">Current range compared with {analytics.data.previousStartDate} → {analytics.data.previousEndDate}.</p></div><span className="rounded-full bg-indigo-500/10 px-3 py-1 text-xs font-medium text-indigo-200">Real database metrics</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{Object.entries(analytics.data.comparison).map(([label, change]) => <div key={label} className="rounded-xl border border-white/10 bg-black/10 p-3"><p className="text-xs capitalize text-slate-500">{label}</p><p className="mt-1 text-lg font-bold">{compact(change.current)}</p><p className={`mt-1 text-xs ${change.percent >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{change.percent >= 0 ? "↑" : "↓"} {Math.abs(change.percent)}%</p></div>)}</div></Card>
      <div className="grid gap-6 lg:grid-cols-2"><Card className="border-white/10 bg-white/[0.045] p-5"><div className="mb-4 flex items-center gap-2"><LineChartIcon className="h-5 w-5 text-cyan-300" /><div><h2 className="font-semibold">Reach over time</h2><p className="text-xs text-slate-400">Views and new subscribers by day.</p></div></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.45} /><XAxis dataKey="date" tick={{ fill: "#94a3b8", fontSize: 11 }} minTickGap={24} /><YAxis tick={{ fill: "#94a3b8", fontSize: 11 }} /><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: 12 }} /><Legend /><Line type="monotone" dataKey="views" name="Views" stroke="#22d3ee" strokeWidth={2} dot={false} /><Line type="monotone" dataKey="subscribers" name="Subscribers" stroke="#a78bfa" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div></Card><Card className="border-white/10 bg-white/[0.045] p-5"><div className="mb-4 flex items-center gap-2"><BarChart3 className="h-5 w-5 text-rose-300" /><div><h2 className="font-semibold">Engagement mix</h2><p className="text-xs text-slate-400">Interactions from real published content.</p></div></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.45} /><XAxis dataKey="date" tick={{ fill: "#94a3b8", fontSize: 11 }} minTickGap={24} /><YAxis tick={{ fill: "#94a3b8", fontSize: 11 }} /><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: 12 }} /><Legend /><Bar dataKey="likes" name="Likes" fill="#fb7185" radius={[4, 4, 0, 0]} /><Bar dataKey="comments" name="Comments" fill="#38bdf8" radius={[4, 4, 0, 0]} /><Bar dataKey="shares" name="Shares" fill="#34d399" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></Card></div>
      <Card className="border-white/10 bg-white/[0.045] p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Recent videos</h2><p className="mt-1 text-sm text-slate-400">Performance from the selected date range.</p></div><Button variant="outline" className="border-white/15 bg-transparent text-white hover:bg-white/10 hover:text-white" onClick={() => setLocation("/videos")}>Open player</Button></div>{analytics.data.recentVideos.length === 0 ? <div className="mt-8 rounded-xl border border-dashed border-white/15 p-8 text-center"><Video className="mx-auto h-8 w-8 text-slate-500" /><p className="mt-3 font-medium">No public videos in this range</p></div> : <div className="mt-6 divide-y divide-white/10">{analytics.data.recentVideos.map((video) => <div key={video.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="truncate font-medium">{video.title}</p><p className="mt-1 text-xs text-slate-500">{new Date(video.createdAt).toLocaleDateString()}</p></div><div className="flex items-center gap-4 text-sm text-slate-300"><span className="flex items-center gap-1"><Eye className="h-4 w-4" />{compact(video.views)}</span><span className="flex items-center gap-1"><Heart className="h-4 w-4" />{compact(video.likes)}</span><span className="flex items-center gap-1"><MessageCircle className="h-4 w-4" />{compact(video.comments)}</span></div></div>)}</div>}</Card>
    </>}</div></main>;
}
