import { ArrowLeft, PlayCircle, UserPlus } from "lucide-react";
import { Link, useParams } from "wouter";
import { Card } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";

export default function HandleProfile() {
  const { handle = "" } = useParams<{ handle: string }>();
  const profile = trpc.profileEdit.getByHandle.useQuery({ handle }, { retry: false, staleTime: 60_000 });
  if (profile.isLoading) return <main className="grid min-h-screen place-items-center bg-[#080b14] text-slate-300"><div className="h-12 w-12 animate-spin rounded-full border-2 border-indigo-300 border-t-transparent" aria-label="Loading profile" /></main>;
  if (!profile.data) return <main className="grid min-h-screen place-items-center bg-[#080b14] p-6 text-white"><Card className="max-w-md border-white/10 bg-white/5 p-8 text-center"><p className="text-sm uppercase tracking-[0.2em] text-indigo-300">TRILLIONER LINK</p><h1 className="mt-3 text-2xl font-bold">Handle not found</h1><p className="mt-2 text-slate-400">This handle may be unavailable or has not been claimed.</p><Link href="/explore"><button className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-950"><ArrowLeft className="h-4 w-4" />Back to explore</button></Link></Card></main>;
  const isCreator = profile.data.accountMode === "creator";
  return <main className="min-h-screen bg-[#080b14] px-4 py-10 text-white sm:px-8"><div className="mx-auto max-w-3xl"><Card className="overflow-hidden border-white/10 bg-white/[0.045]"><div className="h-36 bg-gradient-to-br from-indigo-950 via-slate-900 to-cyan-950 sm:h-48" /><div className="px-6 pb-8"><div className="-mt-12 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-end gap-4"><div className="grid h-24 w-24 place-items-center overflow-hidden rounded-3xl border-4 border-[#080b14] bg-indigo-600 text-3xl font-bold">{profile.data.profileImage ? <img src={profile.data.profileImage} alt="" className="h-full w-full object-cover" /> : (profile.data.name?.[0] ?? "?").toUpperCase()}</div><div><h1 className="text-2xl font-bold">{profile.data.name || `@${profile.data.handle}`}</h1><p className="text-slate-400">@{profile.data.handle}</p></div></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-500 px-5 py-3 font-semibold hover:bg-indigo-400"><UserPlus className="h-4 w-4" />{isCreator ? "Subscribe" : "Follow"}</button></div><p className="mt-6 max-w-2xl text-slate-300">{profile.data.bio || (isCreator ? "Creator content, videos, and community updates." : "Connecting with people and communities on TRILLIONER LINK.")}</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-white/10 bg-black/10 p-4"><p className="text-xs uppercase tracking-wider text-slate-500">{isCreator ? "Subscribers" : "Followers"}</p><p className="mt-1 text-2xl font-bold">—</p></div><div className="rounded-xl border border-white/10 bg-black/10 p-4"><p className="text-xs uppercase tracking-wider text-slate-500">Mode</p><p className="mt-1 font-semibold">{isCreator ? "Creator" : "Personal"}</p></div><div className="rounded-xl border border-white/10 bg-black/10 p-4"><p className="text-xs uppercase tracking-wider text-slate-500">Content</p><p className="mt-1 flex items-center gap-2 font-semibold"><PlayCircle className="h-4 w-4 text-cyan-300" />{isCreator ? "Videos" : "Posts"}</p></div></div></div></Card></div></main>;
}
