import { createContext, useContext, useRef, useState, type ReactNode } from "react";
import { Maximize2, Pause, Play, X } from "lucide-react";
import { Button } from "@/components/ui/button";

export type MiniPlayerItem = { id: number; title: string; videoUrl: string; thumbnailUrl?: string | null; mediaType: "short" | "long" };
type MiniPlayerContextValue = { item: MiniPlayerItem | null; open: (item: MiniPlayerItem) => void; close: () => void; };
const MiniPlayerContext = createContext<MiniPlayerContextValue | undefined>(undefined);

export function MiniPlayerProvider({ children }: { children: ReactNode }) { const [item, setItem] = useState<MiniPlayerItem | null>(null); return <MiniPlayerContext.Provider value={{ item, open: setItem, close: () => setItem(null) }}>{children}</MiniPlayerContext.Provider>; }
export function useMiniPlayer() { const context = useContext(MiniPlayerContext); if (!context) throw new Error("useMiniPlayer must be used within MiniPlayerProvider"); return context; }

export default function MiniPlayer() { const { item, close } = useMiniPlayer(); const videoRef = useRef<HTMLVideoElement>(null); const [playing, setPlaying] = useState(true); if (!item) return null; const toggle = () => { const video = videoRef.current; if (!video) return; if (video.paused) { void video.play(); setPlaying(true); } else { video.pause(); setPlaying(false); } }; const openPiP = async () => { const video = videoRef.current; if (!video) return; if (document.pictureInPictureEnabled && video.requestPictureInPicture) { try { await video.requestPictureInPicture(); } catch { /* Keep the fixed mini-player when browser PiP is unavailable. */ } } }; return <aside aria-label="Mini video player" className="fixed bottom-4 right-4 z-[60] w-[min(21rem,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-cyan-300/30 bg-slate-950/95 shadow-2xl backdrop-blur-xl"><div className="relative aspect-video bg-black"><video ref={videoRef} autoPlay playsInline controls={false} poster={item.thumbnailUrl ?? undefined} src={item.videoUrl} className="h-full w-full object-contain" onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} /><div className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-gradient-to-t from-black/80 to-transparent p-2"><Button variant="ghost" size="icon" aria-label={playing ? "Pause mini-player" : "Play mini-player"} onClick={toggle} className="text-white hover:bg-white/15">{playing ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}</Button><Button variant="ghost" size="icon" aria-label="Open browser Picture-in-Picture" onClick={() => void openPiP()} className="text-white hover:bg-white/15"><Maximize2 className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label="Close mini-player" onClick={close} className="text-white hover:bg-white/15"><X className="h-4 w-4" /></Button></div></div><p className="truncate px-3 py-2 text-xs font-medium text-white">{item.title}</p></aside>; }
